name: 'CI'

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: 'Decode GPG'
      id: unlock_gpg
      env:
        GPG_BASE64: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
      if: ${{ env.GPG_BASE64 }}
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'secring.gpg'
        fileDir: '~/.gradle/'
        encodedString: ${{ secrets.GPG_BASE64 }}

    - uses: gradle/gradle-build-action@v2
      id: run_check
      with:
        arguments: check

    - name: 'Deploy to Nexus'
      id: deploy
      if: steps.run_check.outcome == 'success'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
            publishGalacticraftPublicationToSnapshotsRepository
            -Psigning.keyId=${{secrets.GPG_PRIVATE_KEY}}
            -Psigning.password=${{secrets.GPG_PRIVATE_KEY_PASSPHRASE}}
            -Psigning.secretKeyRingFile=${{ steps.unlock_gpg.outputs.filePath }}

    - name: Capture build artifacts
      if: steps.deploy.outcome == 'success'
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Galacticraft-Legacy_snapshot-preview
        path: |
          build/libs/
          !build/libs/*-deobf.jar
          !build/libs/*-sources.jar
