name: 'CI'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: Fetch Tags
        run: git fetch --unshallow --tags

      - name: 'Cache'
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 'Setup Java'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: 'Mark tag as release'
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE=true" >> $GITHUB_ENV

      - name: 'Build'
        run: ./gradlew build --max-workers 1

      - name: 'Create GitHub release'
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: 'Set Nexus Release Repository Variable'
        if: startsWith(github.ref, 'refs/tags/')
        env:
          URL: ${{ secrets.NEXUS_NEXUS_RELEASE_URL }}
        run: echo "NEXUS_REPOSITORY_URL=$URL" >> $GITHUB_ENV

      - name: 'Set Nexus Snapshot Repository Variable'
        if: |
          startsWith(github.ref, 'refs/heads/') || 
          startsWith(github.ref, 'refs/pull/')
        env:
          URL: ${{ secrets.NEXUS_SNAPSHOT_URL }}
        run: echo "NEXUS_REPOSITORY_URL=$URL" >> $GITHUB_ENV
        
      - name: 'Deploy to Nexus'
        env:
          NEXUS_URL: ${{ env.NEXUS_REPOSITORY_URL }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publish
