name: 'CI'

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/gradle-build-action@v2
      id: run_check
      with:
        arguments: check
        
    - name: 'Variables'
      run: echo RINGFILE="./secring.gpg" >> $GITHUB_ENV

    - name: 'Decode GPG'
      id: unlock_gpg
      if: steps.run_check.outcome == 'success'
      run: |
        echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" >> "${RINGFILE}.b64"
        base64 -d "${RINGFILE}.b64" >> "${RINGFILE}"

    - name: 'Deploy to Nexus'
      id: deploy
      if: steps.unlock_gpg.outcome == 'success'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishGalacticraftPublicationToSnapshotsRepository -Psigning.keyId=${{secrets.GPG_PRIVATE_KEY}} -Psigning.password=${{secrets.GPG_PRIVATE_KEY_PASSPHRASE}} -Psigning.secretKeyRingFile="${RINGFILE}"

    - name: Capture build artifacts
      if: steps.deploy.outcome == 'success'
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Galacticraft-Legacy_snapshot-preview
        path: |
          build/libs/
          !build/libs/*-deobf.jar
          !build/libs/*-sources.jar
